apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ergkb-3lf-python
  janus-idp.io/tekton: ergkb-3lf-python
  backstage.io/kubernetes-id: ergkb-3lf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ergkb-3lf-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
