apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ergkb-3lf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ergkb-3lf-python 
  name: ergkb-3lf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ergkb-3lf-python 
